### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by MrKira34** [Ground-Zerro/DNS-RouteSync-Navigator#1]
На сервере установил вашу вундервафлю. В конце, после запуска, получил такой лог в терминале:
```
2024-08-07 20:05:28,832 - INFO - Файл конфигурации config.ini загружен.
2024-08-07 20:05:28,839 - INFO - Доменные имена загружены из файла filter.txt.
2024-08-07 20:05:28,840 - INFO - DNS сервер запущен 89.110.87.65:53
```
Указываю в настройках WiFi подключения к роутеру DNS в ручную, указываю 89.110.87.65 после чего пробую зайти на любой сайт. Сайт очень долго грузится с шибкой DNS.
При этом на сервере в логах больше ничег не появляется. Никаких записей.
Пробовал в ручную с этого сервера подключиться к роутеру по SSH c параметрами указанными в config.ini - все подключается корректно. Роутер у меня Keenetic Speedster. Так же открыл логи самого кинетика. Не вижу что бы сервер подключался к роутеру.
Куда копать?

**Comment by MrKira34** [comment]
DNS_PROBE_FINISHED_BAD_CONFIG
Вот такая ошибка на всех сайтах

**Comment by Ground-Zerro** [comment]
> На сервере установил вашу вундервафлю. В конце, после запуска, получил такой лог в терминале:
> 
> ```
> 2024-08-07 20:05:28,832 - INFO - Файл конфигурации config.ini загружен.
> 2024-08-07 20:05:28,839 - INFO - Доменные имена загружены из файла filter.txt.
> 2024-08-07 20:05:28,840 - INFO - DNS сервер запущен 89.110.87.65:53
> ```
> 
> Указываю в настройках WiFi подключения к роутеру DNS в ручную, указываю 89.110.87.65 после чего пробую зайти на любой сайт. Сайт очень долго грузится с шибкой DNS. При этом на сервере в логах больше ничег не появляется. Никаких записей. Пробовал в ручную с этого сервера подключиться к роутеру по SSH c параметрами указанными в config.ini - все подключается корректно. Роутер у меня Keenetic Speedster. Так же открыл логи самого кинетика. Не вижу что бы сервер подключался к роутеру. Куда копать?

Если молчит лог значит до скрипта не доходят DNS запросы. Учитывая что браузер ругается ошибкой "DNS_PROBE_FINISHED_BAD_CONFIG" скорее всего на VPS какая-то служба висит на 53 порту занимая его.
Проверить можно `sudo netstat -tuln | grep ':53'` или `sudo ss -tuln | grep ':53'`. 
Или, что тоже бывает, закрыт 53 порт в фаерволе на VPS или у Хостера.
