### ISSUE TITLE
Не совсем вопрос, больше даже предложение.

### ISSUE THREAD

**Issue by MrKira34** [Ground-Zerro/DNS-RouteSync-Navigator#3]
У вас очень занятный проект получился. Пока разбираемся с некоторыми проблемами ( в отдельных вопросах я спрашивал, сейчас тестирую изменения) хотел предложить такую пищу для размышления, не знаю на сколько это возможно "просто" реализовать, но было бы очень уместно. У меня, к примеру, 3 роутера keenetic speedster в нескольких квартирах + у родственников такие (везде выделенный IP, но я кстати не уверен, что он везде прям необходим, можно же DDNS использовать). И не хотелось бы под каждый заводить отдельный сервер. Было бы круто, как-то, возможно, в массив заводить IP адреса всех устройств. Что бы скрипт видел с какого IP к нему прилетел запрос и дальше на этот же IP (роутера) делал ssh и добавлял маршрут. Либо, если так не возможно, то на все сразу добавленные роутеры пробрасывал один и тот же маршрут, возможно, это даже лучше. Если один пользователь Ютуб, условно открыл, получил себе запись, то остальные ее так же уже получат. А учетки типа User, Pass, Port можно одну оставить и просто добавлять ее на все свои роутеры, что бы было меньше заморочек. Это было бы прям супер.
+ Если нужно, могу поделиться. Я немного доделал архитектуру скрипта вашего. Я завернул все в Docker контейнер, сделал образы. + сделал рядом образ WireGuard. Я на роутере поднимаю WireGuard + Socks5.
WireGuard - нужен для того, что бы DNS запросы были зашифрованные. То есть в DNS на роутере я указываю IP адрес WireGuard сервера (10.8.0.1). Сделал это потому, что лично у меня провайдер перехватывает не защищенные запросы к другим DNS, указанным в ручную и подменяет их. А так как они зашифрованные - он этого сделать не может.
Дальше уже ваш скрипт получает IP домена и на роутере создает маршрут, который идет через Socks5, через Socks5 он идет, а не через WireGuard, то же из-за проделок провайдера, но если провайдер WireGuard не блочит, то можно ваш скрипт на интерфейс WireGurad было бы направить и избавится от Socks5.

Вот если бы ваш скрипт, мог подключаться обратно к разным роутерам, указанным списком в него, это было бы очень круто. Тогда можно было бы создать несколько WireGuard пользователей. На каждый роутер свой и один DNS 10.8.0.1

**Comment by Ground-Zerro** [comment]
Интересно. Пойдем по порядку.
Утечка DNS.
Решил проверить как работает скрипт на VPS и столкнулся с этим. Задумался переделать скрипт на DoT чтобы было шифрование. Много сложностей, SSL нужен и т.д. Пока не представляю как к этому подойти. Но из головы не выбрасываю - вещь нужная.

Несколько роутеров.
Сделать наверное можно. Сейчас одно SSH подключение, по идее нужно просто добавить два или три SSH например задать это в config.ini. Это проще DoT ))
Но есть нюансы работы DNS, как например то, что IP у youtube.com для этих трех роутеров может быть разным и еще кучка сложностей. Правильнее будет смотреть от кого получен DNS запрос и на этот же узел отправлять статический маршрут, а это ведет к пересмотру работы IP и DNS кешей в скрипте и другие сложности.

Проектом фактически не пользуюсь, он был задуман как хоть какое-то решение для моего Кинетика без возможности установить entwawre или OpenWRT. Пришел к тому что заказал роутер на котором вся эта магия с маршрутизацией и будет происходить.

Сегодня кстати правил код и сломал обработку ошибки SSH - теперь скрипт сыпется в ошибку, что критически в случае когда он работает как основной DNS сервер на каких-то устройствах. Надо бы исправить.
Что будет с проектом дальше пока не знаю, мне самому он фактически стал не нужен, а остальные люди в подавляющем большинстве пользуются решениями на entwawre и OpenWRT.
Не знаю...

В плане решения насущных проблем есть идея для немного другого подхода. Можно поднять на VPS софтину AD Guard Home которая будет работать основным DNS сервером для целевых машин, к слову он поддерживает DoT, а скрипту будет кидать IP адреса которые уже сам скрипт будет фильтровать и слать на Кинетики как статические маршруты. Плюсами будет отказоустойчивость, шифрование DNS, фильтрация рекламы, более правильная работа самого DNS сервера..
Но это пока не больше чем мысли.

**Comment by Ground-Zerro** [comment]
@MrKira34 

Если на связи еще.

Починил в скрипте проблему с потерей SSH соединения. Она все-таки оставалась в последних версиях.
Скрипт теперь бесконечно будет пытаться его восстановить и при удачной попытке на роутер снова пойдут команды. На время проблем с SSH адреса доменов из фильтра удаляются из IP кеша, это должно гарантировать, что при возобновлении работы SSH они будут добавлены в роутере.

Начал работу по поддержке скриптом DNS over TLS. Чтобы исключить утечку DNS и убрать для провайдера возможность гадить своими подменами.
Но соответственно для DoT нужен домен (можно взять для своего VPS у noip.com) и действующий SSL (можно получить для домена от noip.com у lets encrypt).
Предметно DoT пока не тестировал, возможно он даже работает ))

Пока все.

**Comment by MrKira34** [comment]
Конечно на связи. Сейчас буду тестировать. Если говорим про работу DoT, где указывать домен? Вместо IP сервера?

**Comment by Ground-Zerro** [comment]
> Конечно на связи. Сейчас буду тестировать. Если говорим про работу DoT, где указывать домен? Вместо IP сервера?

Там сложнее все.
Пока не писал инструкций т.к. сам еще разбираюсь.

В кратце: нужно сгенерить SSL сертификат у lets encrypt для своего домена который в свою очередь взять у noIP, положить закрытый ключ и сертификат (файлы fullchain.pem' и 'privkey.pem) в папку со скриптом, или в самом коде скрипта указать к ним прямой путь (строчка: certfile='fullchain.pem', keyfile='privkey.pem').
В config.ini поставить режим mix или dot.

**Comment by Ground-Zerro** [comment]
DoT отменяется.
В сертификатах от Let's Encrypt указывается только DNS имя и нет IP, что необходимо для шифрования в разрезе работы DNS сервера. Без IP в  SAN сервер и хост не могут установить шифрованное соединение.
Можно купить такой SSL но его цена в год выходит далеко за рамки "домашнего проекта" и нецелесообразна.
Попробую почитать про DoH.

**Comment by MrKira34** [comment]
DoH вроде можно настроить с Let's Encrypt, на сколько помню.
По поводу SSH - резюмирую. Все отлично работает. Весь день тестирую, все быстро прописывается и без ошибок.

**Comment by Ground-Zerro** [comment]
DoH с Let's Encrypt завелся, адреса резолвит, маршруты на Кинетика шлет...

Положил пока сюда:
[ПреПреПре_Alpha_DoH_ReliZz](https://cloud.mail.ru/public/m33K/LVYXrdGUc)
Шаблоны инструкций в комплекте.

**Comment by pegakmop** [comment]
Автор, а как с вами связаться в телеграмме? Есть несколько интересных вопросов и предложений, которые думаю вас заинтересуют))

**Comment by Ground-Zerro** [comment]
@pegakmop 

[Канал в ТГ для связи](https://t.me/+iy38m3CTIGExODcy). Надеюсь предложение не связанно с "легким заработком" ибо я чту уголовный кодекс. ))

Проект был написан как временное решение для определенных ситуаций. Если его кто-то и использует, то не более чем пара человек. Особого смысла в его поддержке я не вижу.

**Comment by MrKira34** [comment]
Доброго времени суток. Уже почти год пользуюсь вашим скриптом (версия без DoH, завтра посталю с DoH на тест), все работает идеально. Не на радуюсь. 

Не получилось у вас реализовать поддержку нескольких роутеров? Что бы можно было родственников к скрипту подключить? И не оплачивать отдельно несколько серверов под них.

**Comment by Ground-Zerro** [comment]
@MrKira34 

Ого! Вот это стаж ))
Привет.
Давно перешел на роутер с entware, обратной связи по скрипту никто не давал, запросов не писали. Поэтому проект не развивался.

Раз такое дело - есть идея!
Пришла недавно мысль, что не обязательно шифровать DNS. Это довольно сложно, морока с IP с сертификатми и т.п. Можно вместо этого попробовать обращаться к нему по внутренней сети VPN подключения, которое изначально зашифровано и провайдер никак в него не влезет чтобы подменить DNS ответ.

Как работает (в теории):
В качестве IP адреса DNS-сервера указывается IP адрес VPN сервера, в качестве IP роутера тоже указывается его внутренний VPN адрес.
Например. При подключении к VPN серверу IP сервера 10.10.10.2, а IP клиента (роутера) 10.10.10.4 вот их и использовать для обмена данными.
Роутер будет слать DNS-запросы на 10.10.10.2 и получать ответы, а скрипт будет отправлять SSH команды роутеру на 10.10.10.4. Канал зашифрован, связь "прямая" без промежуточных узлов.

Единственное условие - должна быть включена пересылка пакетов внутри VPN соединения, чтобы клиенты могли видеть друг друга и обмениваться данными.

К тому-же версия с DoH была в альфе и толком не тестировалась, наверняка там есть ошибки.

Есть желание попробовать?

**Comment by MrKira34** [comment]
Я так и делал изначально. Но для этого надо что бы на роутере было поднято VPN соединение. 
И тут есть вопрос)
DNS сервер указывается в настройках подключения Ethernet (кабеля), когда настройки применяется и включаются на этом этапе ещё нет активного VPN подключения. 
То есть:
1) Роутер подключается к интернету в настройках DNS указан внешний IP сервера со скриптом.
2) Поднимается VPN соединение до того же сервера
3) Дальше работу скрипта вы и сами знаете.

А вот если в настройках Ethernet, в качестве DNS сервера указать внутренний адрес сети VPN. То её по факту ещё не существует. И у меня лично не происходит подключения к интернету по кабелю. Как это обойти я так и не понял. 

Пока это писал, осенило. Есть же в настройках роутера, раздел с DNS сторонними, там можно в ручную свои указать. Что если в настройках Ethernet указать DNS провайдера что бы срабатывало подключение. А потом в тех настройках сторонних DNS указывать внутренний DNS, который за VPN находится. По идее так должно работать.


Но тут ещё такая проблема, что например у мой родственницы,  назовём её Люба, у неё провайдер начал блокировать WireGuard обмен пакетами с сервером не происходит. Там в качестве VPN, под ваш скрипт я использую Socks5 - он работает отлично. Но в Socks5 нет такой типа локальной сети. Там так не настроить. То есть это надо, что бы заведомо работали WireGuard и не бросились провайдерами.

Но сам DoH мне по большому счету сейчас не столь важен, сколько важно, что я выше в топике описал. Потому что у меня и без DoH сейчас все работает. Просто я 3 сервера оплачиваю и везде ваш скрипт поднят.
Было бы круто, если бы был 1 сервер, который держал бы несколько ssh соединений. Что бы я в config.ini указал одного например пользователя после этого же пользователя продублировал на роуетерах, один порт указал и его бы включил на роуетерах. И списком IP адреса. Что бы если с одного роутера пришел запрос и сразу бы маршрут прокинулся на все роутеры. Либо что бы маршрут прокидывался на тот роутер, и которого пришёл запрос используя данные из config.ini. тогда это бы решило мои проблемы) А DoH мне в целом не нужен и так все работает.
Я использую ваш скрипт, я его в докер упаковал, могу скинуть линк на гит. Посмотрите как сделал удобно.

**Comment by Ground-Zerro** [comment]
К сожалению на этот проект совсем нет времени.
Ту идею я помню, но не представляю как реализовывать.

Как вариант можно попробовать запускать DNS сервера на одном VPS но на разных портах (и из разных директорий) для разных клиентов. В конфиге навигатора такое предусмотрено, а кинетик допускает указание порта при добавлении DNS сервера.

По подключению не понял. Почему не поднимается VPN без доступа к DNS, обращение к серверу же происходит по IP и DNS не требуется. Или у VPN вместо IP используется доменное имя VPN сервера?

Вместо Wireguard можно использовать Amnezia WireGuard, он доступен на кинетиках начиная с прошивки 4.2.2 (можно сменить канал обновления в роутере на канал разработчика, чтобы обновить старые модели типа AIR на современную прошивку).

Как-то так.

**Comment by Ground-Zerro** [comment]
> К сожалению на этот проект совсем нет времени. Ту идею я помню, но не представляю как реализовывать.
> 
> Как вариант можно попробовать запускать DNS сервера на одном VPS но на разных портах (и из разных директорий/виртуальных окружений/образов докера) для разных клиентов. В конфиге навигатора такое предусмотрено, а кинетик допускает указание порта при добавлении DNS сервера.
> 
> По подключению не понял. Почему не поднимается VPN без доступа к DNS, обращение к серверу же происходит по IP и DNS не требуется. Или у VPN вместо IP используется доменное имя VPN сервера?
> 
> Вместо Wireguard можно использовать Amnezia WireGuard, он доступен на кинетиках начиная с прошивки 4.2.2 (можно сменить канал обновления в роутере на канал разработчика, чтобы обновить старые модели типа AIR на современную прошивку).
> 
> Как-то так.

**Comment by Ground-Zerro** [comment]
К сожалению на этот проект совсем нет времени. Ту идею я помню, но не представляю как реализовывать.
Как вариант можно попробовать запускать DNS сервера на одном VPS но на разных портах (и из разных директорий/виртуальных окружений/образов докера) для разных клиентов. В конфиге навигатора такое предусмотрено, а кинетик допускает указание порта при добавлении DNS сервера.
По подключению не понял. Почему не поднимается VPN без доступа к DNS, обращение к серверу же происходит по IP и DNS не требуется. Или у VPN вместо IP используется доменное имя VPN сервера?
Вместо Wireguard можно использовать Amnezia WireGuard, он доступен на кинетиках начиная с прошивки 4.2.2 (можно сменить канал обновления в роутере на канал разработчика, чтобы обновить старые модели типа AIR на современную прошивку).
Как-то так.
