### ISSUE TITLE
Ошибки работы на Ubuntu 22.04.5 LTS

### ISSUE THREAD

**Issue by Ya-Lexand** [Ground-Zerro/DNS-RouteSync-Navigator#4]
Привет, дорого Автор!
Понимаю, что проект уже не интересен, но мне как раз понадобился, а скрипт не работает. Питон выдаёт следующую ошибку:

lo@freezing-move:~/route-sync/DNS-RouteSync-Navigator$ bash start.sh
RouterSyncNavigator:
1. Установить как системную службу
2. Запустить в Python
3. Ничего не делать
Выберите опцию (1/2/3): 2
/home/solo/.local/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:29: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/solo/.local/lib/python3.10/site-packages/asyncssh/crypto/cipher.py:30: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import TripleDES
Traceback (most recent call last):
  File "/home/solo/route-sync/DNS-RouteSync-Navigator/main.py", line 9, in <module>
    import asyncssh
  File "/home/solo/.local/lib/python3.10/site-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/home/solo/.local/lib/python3.10/site-packages/asyncssh/agent.py", line 34, in <module>
    from .public_key import KeyPairListArg, SSHCertificate, SSHKeyPair
  File "/home/solo/.local/lib/python3.10/site-packages/asyncssh/public_key.py", line 35, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/home/solo/.local/lib/python3.10/site-packages/asyncssh/crypto/__init__.py", line 58, in <module>
    from .x509 import X509Certificate, X509Name, X509NamePattern
  File "/home/solo/.local/lib/python3.10/site-packages/asyncssh/crypto/x509.py", line 32, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
Ошибка при выполнении скрипта main.py.

lo@freezing-move:~/route-sync/DNS-RouteSync-Navigator$ python3 -V
Python 3.10.12

**Comment by Ground-Zerro** [comment]
Старая версия python, Из вариантов поставить более новый Python, хотя бы 3.12, обновить pip и заново подтянуть зависимости.
```
sudo apt install python3.12
```
и pip
```
sudo apt install python3-pip
```


> 3\. X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY

Старая версия библиотеки.
Постоянно на VM и некоторых VPS эта ошибка вываливалась. 
Четкой инструкции как чинить не знаю.
Как вариант:
```
pip install --upgrade cryptography
```
потом
```
pip install --upgrade pyOpenSSL
```
Если версия OpenSSL ниже 1.1.1, проверить можно:
```
openssl version
```
то попробовать поставить свежее:
```
sudo apt update
sudo apt install openssl
```


Какая ОС? если 18.04 то без вариантов - не починить.
Мне надоело её вылавливать, в итоге перешел на Ubuntu 22.04

**Update**
А, увидел версию ОС.
Обновляй питон, пип и open ssl.

**Comment by Ground-Zerro** [comment]
> Понимаю, что проект уже не интересен

Не то чтобы не интересен. Поддерживаю что могу. xBox на днях добавился.
Людям не интересен скорее, предпочитают качать сомнительные, зато готовые bat'ники от неизвестно кого.

**Comment by Ya-Lexand** [comment]
Помогло! Правда что именно, бубен или заклинания "такой-то матери" не могу сказать и в каком порядке не понятно.
Тут ещё мне помешало то, что сначала я всё пробовал от простого пользователя, а в итоге понадобились права root чтобы поднять локальный DNS-сервис. И пришлось уже от рута делать так:
pip install --upgrade cryptography
pip install --upgrade pyOpenSSL
bash start.sh

**Comment by Ground-Zerro** [comment]
@Ya-Lexand 
Это хорошо.
Держи версию с поддержкой DoH ))
[Скачать](https://cloud.mail.ru/public/m33K/LVYXrdGUc)
Инструкции по шагам внутри архива.

PS
На сервер все рекомендуется делать от root. Дай пользователю под которым работаешь root права, чтоб sudo не использовать.

Откройте файл с помощью безопасного редактора:
```
sudo visudo
```
Добавьте строку, позволяющую пользователю выполнять команды от имени root:
```
имя_пользователя ALL=(ALL:ALL) ALL
```

**Comment by Ground-Zerro** [comment]
@Ya-Lexand 

А что за роутер то хоть? KN-??
